"""create offer table

Revision ID: 062eaa6547b0
Revises: 95135e16e155
Create Date: 2026-07-24 14:27:53.243435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062eaa6547b0'
down_revision: Union[str, Sequence[str], None] = '95135e16e155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=150), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('variant', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('first_registration', sa.String(length=10), nullable=True),
    sa.Column('power_kw', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('drivetrain', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_dealer_id'), 'offer', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_offer_external_id'), 'offer', ['external_id'], unique=False)
    op.create_index(op.f('ix_offer_source'), 'offer', ['source'], unique=False)
    op.create_index(op.f('ix_offer_vin'), 'offer', ['vin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_vin'), table_name='offer')
    op.drop_index(op.f('ix_offer_source'), table_name='offer')
    op.drop_index(op.f('ix_offer_external_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_dealer_id'), table_name='offer')
    op.drop_table('offer')
    # ### end Alembic commands ###
