"""extend dealer for BMW sync

Revision ID: 95135e16e155
Revises: 32abeba6ad71
Create Date: 2026-07-24 12:54:47.037381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95135e16e155'
down_revision: Union[str, Sequence[str], None] = '32abeba6ad71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Zunächst neue Pflichtfelder temporär nullable bzw. mit Server-Default anlegen.
    op.add_column(
        "dealer",
        sa.Column("bmw_dealer_id", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column(
            "distribution_partner_id",
            sa.String(length=50),
            nullable=True,
        ),
    )

    op.add_column(
        "dealer",
        sa.Column("outlet_id", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("street", sa.String(length=200), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("postal_code", sa.String(length=20), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("country", sa.String(length=10), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("latitude", sa.Float(), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("longitude", sa.Float(), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("homepage", sa.String(length=500), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("new_car_email", sa.String(length=255), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("new_car_phone", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("used_car_email", sa.String(length=255), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column("used_car_phone", sa.String(length=50), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column(
            "new_car_sales",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "dealer",
        sa.Column(
            "used_car_sales",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "dealer",
        sa.Column(
            "is_published",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.add_column(
        "dealer",
        sa.Column("last_sync", sa.DateTime(), nullable=True),
    )

    op.add_column(
        "dealer",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # Vorhandenen Testdatensätzen eine eindeutige Übergangs-ID geben.
    op.execute(
        """
        UPDATE dealer
        SET bmw_dealer_id = 'legacy-' || id
        WHERE bmw_dealer_id IS NULL
        """
    )

    # Erst jetzt wird die BMW-ID verpflichtend.
    op.alter_column(
        "dealer",
        "bmw_dealer_id",
        existing_type=sa.String(length=50),
        nullable=False,
    )

    op.create_index(
        op.f("ix_dealer_bmw_dealer_id"),
        "dealer",
        ["bmw_dealer_id"],
        unique=True,
    )

    # Server-Defaults werden nur für die Migration benötigt.
    op.alter_column(
        "dealer",
        "new_car_sales",
        server_default=None,
    )
    op.alter_column(
        "dealer",
        "used_car_sales",
        server_default=None,
    )
    op.alter_column(
        "dealer",
        "is_published",
        server_default=None,
    )
    op.alter_column(
        "dealer",
        "updated_at",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dealer_bmw_dealer_id'), table_name='dealer')
    op.drop_column('dealer', 'updated_at')
    op.drop_column('dealer', 'last_sync')
    op.drop_column('dealer', 'is_published')
    op.drop_column('dealer', 'used_car_sales')
    op.drop_column('dealer', 'new_car_sales')
    op.drop_column('dealer', 'used_car_phone')
    op.drop_column('dealer', 'used_car_email')
    op.drop_column('dealer', 'new_car_phone')
    op.drop_column('dealer', 'new_car_email')
    op.drop_column('dealer', 'homepage')
    op.drop_column('dealer', 'longitude')
    op.drop_column('dealer', 'latitude')
    op.drop_column('dealer', 'country')
    op.drop_column('dealer', 'postal_code')
    op.drop_column('dealer', 'street')
    op.drop_column('dealer', 'outlet_id')
    op.drop_column('dealer', 'distribution_partner_id')
    op.drop_column('dealer', 'bmw_dealer_id')
    # ### end Alembic commands ###
